---
- name: K3s 마스터 노드 설치 및 설정
  hosts: master
  become: yes
  tasks:
    - name: K3s 설치 스크립트 실행
      shell: "curl -sfL https://get.k3s.io | sh -"
      args:
        creates: /usr/local/bin/k3s

    - name: 마스터 노드의 클러스터 조인 토큰 값 가져오기
      command: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_token
      changed_when: false

- name: K3s 워커 노드 설치 및 클러스터 조인
  hosts: workers
  become: yes
  tasks:
    - name: K3s 설치 및 마스터 노드에 조인
      shell: >
        curl -sfL https://get.k3s.io |
        K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443
        K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token'].stdout }}
        sh -
      args:
        creates: /usr/local/bin/k3s
